create table sequence_step as
select instruction
from
  input,
  regexp_split_to_table(line, ',') as instruction;

create function hash_next_char(int, text) returns int return (
  ($1 + ascii($2)) * 17 % 256
);

create aggregate hash_next_char(text) (
    sfunc = hash_next_char,
    stype = int,
    initcond = '0'
);

create function hash(text) returns int return (
  select hash_next_char(char)
  from string_to_table($1, null) as char
);

select sum(hash(instruction))
from sequence_step;
