drop function if exists find_common_item(text[]);
\include_relative parse.psql

create or replace function split_by_compartment(rucksack_items text) returns text[]
  return (
    select array[
      substr(rucksack_items, 1, size),
      substr(rucksack_items, 1 + size, size)
    ]
    from
      (select char_length(rucksack_items) / 2) as _ (size)
  );

select sum(priority(find_common_item(split_by_compartment(rucksack_items)))) from input;
